# Generated by Django 3.1.1 on 2020-09-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('contact', models.CharField(default='', max_length=255)),
                ('password', models.BinaryField()),
                ('group', models.CharField(default='user', max_length=255)),
            ],
        ),
    ]
