# Generated by Django 3.1.1 on 2020-09-11 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalrequest',
            old_name='expire_at',
            new_name='rent_until',
        ),
    ]
