# Generated by Django 3.1.1 on 2020-09-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0002_auto_20200911_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerrequest',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
