# Generated by Django 3.1.1 on 2020-09-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='rent_until',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
