# Generated by Django 3.1.1 on 2020-09-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_rent_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='returning',
            field=models.BooleanField(default=False),
        ),
    ]
