# Generated by Django 3.1.1 on 2020-09-12 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_rent_until'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrecord',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipment'),
        ),
    ]
